---
# tasks file for ITM_zimbra_install
- name: Generating variables
  block:
    - name: randomham
      shell: date +%s|sha256sum|base64|head -c 10
      register: randomham

    - name: randomspam
      shell: date +%s|sha256sum|base64|head -c 10
      register: randomspam

    - name: randomvirus
      shell: date +%s|sha256sum|base64|head -c 10
      register: randomvirus

- name: Manipulating files, packages and services
  block:
    - name: Configuring hostname
      shell: hostnamectl set-hostname {{ srv_hostname }}

    - name: Configuring /etc/hosts
      lineinfile:
        path: /etc/hosts
        insertbefore: '^127.0.0.1'
        line: '{{ ansible_default_ipv4.address }} {{ ansible_fqdn }} {{ ansible_hostname }}'

    - name: Installing packages
      yum:
        name: "{{ item }}"
        state: latest
      with_items:
        - 'perl'
        - 'net-tools'
        - 'nmap-ncat'
        - 'dnsmasq'

    - name: System update
      yum:
        name: '*'
        state: latest

    - name: Moving dnsmasq to .original
      copy:
        src: /etc/dnsmasq.conf
        dest: /etc/dnsmasq.conf.original

    - name: Configure dnsmasq
      template:
        src: dnsmasq.conf.j2
        dest: /etc/dnsmasq.conf
        owner: root
        group: root
        mode: 644

    - name: Start and enable dnsmasq service
      service:
        name: dnsmasq
        state: started
        enabled: true

    - name: create /tmp/zcs directory
      file:
        path: /tmp/zcs
        state: directory

    - name: Copy config script file
      template:
        src: 'installZimbraScript.j2'
        dest: /tmp/zcs/installZimbraScript

    - name: Copy config script file
      template:
        src: 'installZimbra-keystrokes.j2'
        dest: /tmp/zcs/installZimbra-keystrokes

- name: Installing Zimbra
  block:
    - name: version
      shell: rpm -qa '(oraclelinux|sl|redhat|centos)-release(|-server)'|cut -d"." -f3
      register: version

    - name: Downloading Zimbra Collaboration 8.7.11 for CentOS/RedHat 7
      get_url:
        url: https://files.zimbra.com/downloads/8.7.11_GA/zcs-8.7.11_GA_1854.RHEL7_64.20170531151956.tgz
        dest: /tmp/zcs

    - name: Unarchive zimbra file
      unarchive:
        src: /tmp/zcs/zcs-8.7.11_GA_1854.RHEL7_64.20170531151956.tgz
        dest: /tmp/zcs
        remote_src: yes

    - name: Installing Zimbra Collaboration just the Software
      shell: ./install.sh -s < /tmp/zcs/installZimbra-keystrokes
      args:
        chdir: /tmp/zcs/zcs-8.7.11_GA_1854.RHEL7_64.20170531151956

    - name: Installing Zimbra Collaboration injecting the configuration
      shell: /opt/zimbra/libexec/zmsetup.pl -c /tmp/zcs/installZimbraScript

    - name: Change to zimbra user and execute zmcontrol restart
      shell: su - zimbra -c 'zmcontrol restart'
      when: version.stdout == 'el7'
