---
- name: restart dnsmasq
  service:
    name: dnsmasq
    state: restarted

- name: Restart firewalld service
  service:
    name: firewalld
    state: restarted
    
- name: display_message
  debug:
    msg: "You must copy the local file /tmp/installZimbra-keystrokes ..... for backup! "
